# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: build-dotnet-library

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
permissions:
  packages: write
  contents: read
  
jobs:
  build-dotnet-library:
    uses: ktsu-io/workflows/.github/workflows/build-dotnet-library.yml@main
    secrets: inherit
